"""init_alembic

Revision ID: f051d098fc2f
Revises:
Create Date: 2025-01-23 21:48:22.632496

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f051d098fc2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tron_wallet_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__tron_wallet_query'))
    )
    op.create_index(op.f('ix__tron_wallet_query__address'), 'tron_wallet_query', ['address'], unique=False)
    op.create_index(op.f('ix__tron_wallet_query__id'), 'tron_wallet_query', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__tron_wallet_query__id'), table_name='tron_wallet_query')
    op.drop_index(op.f('ix__tron_wallet_query__address'), table_name='tron_wallet_query')
    op.drop_table('tron_wallet_query')
    # ### end Alembic commands ###
